CREATE TABLE words (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language VARCHAR(8) NOT NULL,
    text VARCHAR(128) NOT NULL
);

CREATE TABLE rooms (
    id UUID PRIMARY KEY,
    code VARCHAR(4) NOT NULL UNIQUE,
    language VARCHAR(8) NOT NULL,
    host_player_id UUID NOT NULL,
    status VARCHAR(16) NOT NULL
);

CREATE TABLE players (
    id UUID PRIMARY KEY,
    room_id UUID NOT NULL REFERENCES rooms(id),
    name VARCHAR(64) NOT NULL,
    team VARCHAR(8),
    role VARCHAR(16),
    is_host BOOLEAN NOT NULL
);

CREATE TABLE games (
    id UUID PRIMARY KEY,
    room_id UUID NOT NULL UNIQUE REFERENCES rooms(id),
    starting_team VARCHAR(8) NOT NULL,
    current_team VARCHAR(8) NOT NULL,
    phase VARCHAR(16) NOT NULL,
    clue_word VARCHAR(64),
    clue_count INTEGER,
    guesses_remaining INTEGER NOT NULL,
    winner_team VARCHAR(8)
);

CREATE TABLE cards (
    id UUID PRIMARY KEY,
    game_id UUID NOT NULL REFERENCES games(id),
    position INTEGER NOT NULL,
    word VARCHAR(128) NOT NULL,
    card_type VARCHAR(16) NOT NULL,
    revealed BOOLEAN NOT NULL
);

CREATE INDEX idx_players_room_id ON players(room_id);
CREATE INDEX idx_cards_game_id ON cards(game_id);
